### ISSUE TITLE
spliceAI annotations hg19

### ISSUE THREAD

**Issue by MariaRH** [mobidic/MPA#11]
How can I get spliceAI annotations hg19?

**Comment by vidboda** [comment]
Hi @MariaRH ,
please use the download link below to get the dataset (hg19). Please note that this link is temporary.
https://filesender.renater.fr/?s=download&token=b1dc762a-f485-beb3-9645-287a8dd93f39

**Comment by MariaRH** [comment]
Thank you so much!

**Comment by vidboda** [comment]
Issue closed but we will provide a more permanent solution if someone asks again for this dataset
