### ISSUE TITLE
Final score and adjusted score not working

### ISSUE THREAD

**Issue by kyauy** [mobidic/MPA#6]
MPA_available and MPA_deleterious is working but adjusted and final score give a 0 score for all variant. 

Can you fix this ? :)

**Comment by Char-Al** [comment]
Not for me...

**Output example :**
> chr1	10	.	N	N	.	PASS	[..];MPA_adjusted=1.0;MPA_available=10;MPA_deleterious=1;MPA_final_score=1.0;MPA_impact=NULL;MPA_ranking=7	[...]

**Comment by Char-Al** [comment]
Corrected !
It seems to be an error occur with python 2.x !
