### ISSUE TITLE
MPA final_score bug

### ISSUE THREAD

**Issue by kyauy** [mobidic/MPA#7]
For missense variants (rank 7), there is a bug in MPA final_score, which are always at 10.
MPA_adjusted works. 

You can find the test.vcf at /home/thomasG/test.vcf on minimonster.
/home/thomasG/out file is the test.vcf processed with MPA, where you can find the error. 

Can you fix it ? Thank you very much !!!

**Comment by Char-Al** [comment]
Corrected !

Ty
